;;; org-dayflow-demo.el --- Generated data to develop against  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 yoshzucker

;; Author: yoshzucker
;; URL: https://github.com/yoshzucker/org-dayflow

;; This file is not part of GNU Emacs.

;;; Commentary:

;; A few weeks of work, generated.  Not loaded by `org-dayflow' -- it exists
;; so the package can be looked at on a machine with no data of its own, or
;; with data too private to open in front of anybody.
;;
;; Two decisions shape it, the same two org-foresight's demo is built on.
;;
;; Dates are computed, never written down.  A fixture with literal dates is
;; right on the day it is written and misleading forever after: a timeline is
;; a picture of where today sits among what is coming, and a file that thinks
;; today is last spring cannot draw it.  `org-dayflow-demo-regenerate'
;; rewrites everything relative to now, so it is always the right shape, and
;; re-running it is the way back after moving things about.
;;
;; The data lives apart from the real files and is reached by a toggle.  The
;; timeline is read at a glance and the buffer is named the same either way,
;; so a demo mixed into the real agenda would be a screen nobody could tell
;; from their own week.  Switching off puts the files back and kills the
;; buffers rather than leaving invented work on the screen.
;;
;; What it is built to show is what the view is for: a week that fits, and
;; headings in the order they were written.  The work is in chunks, and the
;; chunks stay together -- which is the one thing a timeline can say that a
;; list of next actions, sorted by date, cannot.

;;; Code:

(require 'org)
(require 'org-dayflow)

(defgroup org-dayflow-demo nil
  "Generated data for developing org-dayflow."
  :group 'org-dayflow
  :prefix "org-dayflow-demo-")

(defcustom org-dayflow-demo-directory
  (locate-user-emacs-file "org-dayflow-demo/")
  "Where the generated demo files are written.
Machine-local and disposable: everything in it is rewritten by
`org-dayflow-demo-regenerate'."
  :type 'directory
  :group 'org-dayflow-demo)

(defvar org-dayflow-demo--saved nil
  "State captured when `org-dayflow-demo-mode' was switched on.")

;;;; Dates, as offsets from today

(defun org-dayflow-demo--date (offset)
  "Return \"YYYY-MM-DD Day\" for OFFSET days from today."
  (format-time-string "%Y-%m-%d %a" (time-add nil (days-to-time offset))))

(defun org-dayflow-demo--stamp (offset &optional from to)
  "Return an active timestamp OFFSET days out.
FROM and TO are \"HH:MM\" strings."
  (concat "<" (org-dayflow-demo--date offset)
          (when from (concat " " from))
          (when (and from to) (concat "-" to))
          ">"))

(defun org-dayflow-demo--entry (todo title &rest props)
  "Return one heading: TODO TITLE, then PROPS as written lines.
Each of PROPS is a line already formed -- a SCHEDULED, a DEADLINE, a
timestamp, a property drawer."
  (concat "* " (if todo (concat todo " ") "") title "\n"
          (mapconcat #'identity (delq nil props) "\n")
          (if (delq nil props) "\n" "")))

(defun org-dayflow-demo--cat (name)
  "Return a property drawer setting CATEGORY to NAME."
  (concat ":PROPERTIES:\n:CATEGORY: " name "\n:END:"))

;;;; The data

(defun org-dayflow-demo--work ()
  "Return the work file: three pieces of work, each in one piece.

Written in the order they happen, because that is the order the view draws
them in.  The point being demonstrated is that a chunk stays a chunk: the
three rows of the migration sit together whatever their dates are, which a
list sorted by date would have scattered through the week."
  (concat
   "#+title: Work (org-dayflow demo)\n"
   "# Generated by org-dayflow-demo-regenerate.  Edits will be lost.\n\n"
   ;; A piece of work already under way, running through the middle of the
   ;; week: something started, something today, something with a date on it.
   (org-dayflow-demo--entry
    "DONE" "移行の段取りを決める"
    (concat "SCHEDULED: " (org-dayflow-demo--stamp -4))
    (org-dayflow-demo--cat "work"))
   (org-dayflow-demo--entry
    "ONGO" "旧サーバの棚卸し"
    (concat "SCHEDULED: " (org-dayflow-demo--stamp -1))
    (concat "DEADLINE: " (org-dayflow-demo--stamp 2))
    (org-dayflow-demo--cat "work"))
   (org-dayflow-demo--entry
    "NEXT" "移行手順のレビュー依頼"
    (concat "SCHEDULED: " (org-dayflow-demo--stamp 0))
    (org-dayflow-demo--cat "work"))
   (org-dayflow-demo--entry
    "NEXT" "切り替えの当日作業"
    (concat "SCHEDULED: " (org-dayflow-demo--stamp 5))
    (concat "DEADLINE: " (org-dayflow-demo--stamp 5))
    (org-dayflow-demo--cat "work"))
   ;; A second piece, deliberately interleaved in time and not in the file.
   (org-dayflow-demo--entry
    "NEXT" "四半期の数字をまとめる"
    (concat "SCHEDULED: " (org-dayflow-demo--stamp 1))
    (concat "DEADLINE: " (org-dayflow-demo--stamp 8))
    (org-dayflow-demo--cat "work"))
   (org-dayflow-demo--entry
    "NEXT" "報告の草案を書く"
    (concat "SCHEDULED: " (org-dayflow-demo--stamp 3))
    (org-dayflow-demo--cat "work"))
   (org-dayflow-demo--entry
    "WAIT" "経理からの確認待ち"
    (concat "SCHEDULED: " (org-dayflow-demo--stamp 4))
    (org-dayflow-demo--cat "work"))
   ;; And one thing past the edge of each longer period, so that going out a
   ;; step always reveals something.  A month that shows the week's rows and
   ;; nothing else demonstrates nothing about being a month.
   (org-dayflow-demo--entry            ; past the month, inside the quarter
    "NEXT" "年度計画の下書き"
    (concat "DEADLINE: " (org-dayflow-demo--stamp 24))
    (org-dayflow-demo--cat "work"))
   (org-dayflow-demo--entry            ; past the quarter, inside the year
    "NEXT" "監査の準備"
    (concat "DEADLINE: " (org-dayflow-demo--stamp 130))
    (org-dayflow-demo--cat "work"))))

(defun org-dayflow-demo--calendar ()
  "Return the calendar file: what the days already have in them.

Appointments rather than tasks, with hours on them, so the `day' period has
something to show and the others have something that is not a task."
  (concat
   "#+title: Calendar (org-dayflow demo)\n"
   "# Generated by org-dayflow-demo-regenerate.  Edits will be lost.\n\n"
   (org-dayflow-demo--entry
    nil "定例会議"
    (org-dayflow-demo--stamp 0 "10:00" "11:00")
    (org-dayflow-demo--cat "meeting"))
   (org-dayflow-demo--entry
    nil "顧客とのすり合わせ"
    (org-dayflow-demo--stamp 2 "14:00" "15:30")
    (org-dayflow-demo--cat "meeting"))
   (org-dayflow-demo--entry
    nil "こうたの発表会"
    (org-dayflow-demo--stamp 6 "13:00" "16:00")
    (org-dayflow-demo--cat "family"))
   (org-dayflow-demo--entry
    nil "歯科"
    (org-dayflow-demo--stamp 9 "18:30" "19:15")
    (org-dayflow-demo--cat "personal"))))

(defun org-dayflow-demo-files ()
  "Return the demo Org files as a list of absolute paths."
  (mapcar (lambda (name) (expand-file-name name org-dayflow-demo-directory))
          '("work.org" "calendar.org")))

;;;###autoload
(defun org-dayflow-demo-regenerate ()
  "Write the demo files afresh, dated relative to today.
Also the way back to a known state after rescheduling things in the view."
  (interactive)
  (make-directory org-dayflow-demo-directory t)
  (pcase-dolist (`(,name . ,fn)
                 `(("work.org" . ,#'org-dayflow-demo--work)
                   ("calendar.org" . ,#'org-dayflow-demo--calendar)))
    (let ((path (expand-file-name name org-dayflow-demo-directory)))
      (when-let ((buf (get-file-buffer path)))
        (with-current-buffer buf (set-buffer-modified-p nil))
        (kill-buffer buf))
      (with-temp-file path (insert (funcall fn)))))
  (when (called-interactively-p 'interactive)
    (message "Demo data regenerated in %s" org-dayflow-demo-directory))
  (org-dayflow-demo-files))

(defun org-dayflow-demo--kill-views ()
  "Kill every Dayflow buffer, so none is left showing invented work."
  (dolist (buf (buffer-list))
    (when (string-prefix-p "*Org Dayflow(" (buffer-name buf))
      (kill-buffer buf))))

;;;###autoload
(define-minor-mode org-dayflow-demo-mode
  "Point Dayflow at generated demo data instead of the real files.

Switching on regenerates the data, redirects `org-agenda-files', and opens
the view.  Switching off puts the files back and kills the Dayflow buffers:
the buffer is named for its period and not for where its rows came from, so
a demo left on the screen is a week nobody could tell from their own.

It also declares the keywords and the category colours the generated files
are written in.  The promise a demo makes is that it can be looked at before
anything has been configured, and on a bare Emacs `NEXT' is not a keyword and
a category is not a colour -- the view would be there, and empty, and grey."
  :global t
  :group 'org-dayflow-demo
  :lighter " Dayflow-demo"
  (if org-dayflow-demo-mode
      (progn
        (setq org-dayflow-demo--saved
              (list :agenda-files (bound-and-true-p org-agenda-files)
                    :todo-keywords org-todo-keywords
                    :category-faces org-dayflow-category-faces))
        ;; Set before the files are visited: Org reads `org-todo-keywords'
        ;; when a buffer enters `org-mode', so a buffer already open would
        ;; keep the old ones and every NEXT would be an ordinary heading.
        (setq org-todo-keywords
              '((sequence "NEXT" "ONGO" "|" "DONE" "CANCEL")
                (sequence "WAIT" "|" "DELEG")))
        (org-dayflow-demo-regenerate)
        (setq org-agenda-files (org-dayflow-demo-files))
        ;; What the generated categories mean.  Two colours and no more: work
        ;; and the house, which is the distinction a week is actually read
        ;; for.
        (setq org-dayflow-category-faces
              '(("work"     . font-lock-keyword-face)
                ("meeting"  . font-lock-keyword-face)
                ("family"   . font-lock-string-face)
                ("personal" . font-lock-doc-face)))
        (org-dayflow-demo--kill-views)
        (org-dayflow-display)
        (message "Demo data active; +/- change the period, / filters, q quits"))
    (setq org-agenda-files (plist-get org-dayflow-demo--saved :agenda-files)
          org-todo-keywords (plist-get org-dayflow-demo--saved :todo-keywords)
          org-dayflow-category-faces
          (plist-get org-dayflow-demo--saved :category-faces))
    (org-dayflow-demo--kill-views)
    (message "Demo data off; Dayflow back to the real files")))

(provide 'org-dayflow-demo)

;;; org-dayflow-demo.el ends here
